### ISSUE TITLE
Cargo improvements and bugs

### ISSUE THREAD

**Issue by jethrogb** [rust-lang-nursery/portability-wg#5]
This is a tracking issue for proposed changes to cargo that could aid 
portability.

* Conditional compilation based on a dependent's choices.
* Target-specific cargo features
* #4

- Post https://github.com/rust-lang/rfcs/pull/1133 concerns
  - [ ] https://github.com/rust-lang/cargo/issues/5002: Explicit standard library dependencies
  - [ ] https://github.com/rust-lang/cargo/issues/5003: Implicit standard library dependencies
  - [x] https://github.com/rust-lang/cargo/issues/4499: @Ericson2314 left comment about `[patch]` for std-lib libraries, thinks issue might by closed in mistake cause cannot find docs
- [ ] https://github.com/rust-lang/cargo/issues/4866: cross compilation totally breaks `build.rs`
  - https://github.com/rust-lang/cargo/issues/4866#issuecomment-362930403 shows that `Cargo.lock` doesn't handle platform-specific dependencies properly either

**Comment by Ericson2314** [comment]
At the end of https://github.com/rust-lang/rfcs/pull/1133 I carved off some stand-alone issues that can be addressed relatively independently. (*edit* added above).

----

@jethrogb seeing you copied my issues in to the OP, I embellished that and removed from here. In general, I was wondering what you think of non-authors editing the OP. It's convenient to put things there, also but don't want to put words into other people's mouths, so no obvious solution IMO.

**Comment by jethrogb** [comment]
https://github.com/jamesmunns/rfcs/pull/1

https://internals.rust-lang.org/t/pre-rfc-std-aware-cargo/9450
